
language: java

before_install:
  – chmod a+x gradlew
jdk:
  - openjdk8

sudo: required

script:
  - ./gradlew clean build -i --continue

deploy:
  provider: heroku
  api_key: $HEROKU_TOKEN
  app: "book-demo-store-yemaneyw"
